spring.application.name=auth-service
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/quickbite_db
spring.datasource.username=User
spring.datasource.password=User
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
